### ISSUE TITLE
testing fails during `mvn clean install`

### ISSUE THREAD

**Issue by egonw** [PathVisio/libGPML#16]
When I do:

```shell
cd org.pathvisio.lib
mvn clean install
```

I get these JUnit test fails:

```
[INFO] Running org.pathvisio.io.TestConvertToGPML2013a
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.pathvisio.io.TestConvertToGPML2013a
[ERROR] testConvertToGPML2013a(org.pathvisio.io.TestConvertToGPML2013a)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestConvertToGPML2013a.testConvertToGPML2013a(TestConvertToGPML2013a.java:55)

[INFO] Running org.pathvisio.io.TestConvertToGPML2021WithXref
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in org.pathvisio.io.TestConvertToGPML2021WithXref
[ERROR] testConvertToGPML2021(org.pathvisio.io.TestConvertToGPML2021WithXref)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestConvertToGPML2021WithXref.testConvertToGPML2021(TestConvertToGPML2021WithXref.java:51)

[INFO] Running org.pathvisio.io.TestReadWriteGPML2021
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.pathvisio.io.TestReadWriteGPML2021
[ERROR] testReadWriteGPML2021(org.pathvisio.io.TestReadWriteGPML2021)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestReadWriteGPML2021.testReadWriteGPML2021(TestReadWriteGPML2021.java:58)

[INFO] Running org.pathvisio.io.TestConvertToGPML2021
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.pathvisio.io.TestConvertToGPML2021
[ERROR] testConvertToGPML2021(org.pathvisio.io.TestConvertToGPML2021)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestConvertToGPML2021.testConvertToGPML2021(TestConvertToGPML2021.java:57)

[INFO] Running org.pathvisio.io.TestReadWriteNewFeatures
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.pathvisio.io.TestReadWriteNewFeatures
[ERROR] testNewFeatures(org.pathvisio.io.TestReadWriteNewFeatures)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestReadWriteNewFeatures.testNewFeatures(TestReadWriteNewFeatures.java:55)

[INFO] Running org.pathvisio.io.TestAllReadWriteGPML2013a
null
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.pathvisio.io.TestAllReadWriteGPML2013a
[ERROR] testReadWriteGPML2013a(org.pathvisio.io.TestAllReadWriteGPML2013a)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestAllReadWriteGPML2013a.testReadWriteGPML2013a(TestAllReadWriteGPML2013a.java:56)

[INFO] Running org.pathvisio.io.TestAllConvertToGPML2021
null
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.pathvisio.io.TestAllConvertToGPML2021
[ERROR] testConvertToGPML2021(org.pathvisio.io.TestAllConvertToGPML2021)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestAllConvertToGPML2021.testConvertToGPML2021(TestAllConvertToGPML2021.java:53)

[INFO] Running org.pathvisio.io.TestAllReadWriteGPML2021
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.pathvisio.io.TestAllReadWriteGPML2021
[ERROR] testReadWriteGPML2021(org.pathvisio.io.TestAllReadWriteGPML2021)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at org.pathvisio.io.TestAllReadWriteGPML2021.testReadWriteGPML2021(TestAllReadWriteGPML2021.java:54)
```

I cannot push to Sonatype before these are fixed.

**Comment by Finterly** [comment]
compile issues fixed. Some of the read/write/conversion tests read from or write to local folders. They have been moved to a separate project for just conversions.
